### ISSUE TITLE
lag spikes when using menu commands

### ISSUE THREAD

**Issue by gameinstructorl4d2** [semihM/project_smok#46]
title.

**Comment by semihM** [comment]
Cause of this is probably the size of the menu being too big. 

There are some ways to get rid of some of the redundant menus, but they require updates to the commands the menus relate to.

 I will take a look when I have time.

**Comment by semihM** [comment]
Reduced the lag as much as I could in the last release [**v3.3.0**](https://github.com/semihM/project_smok/releases/tag/v3.3.0)
