### ISSUE TITLE
Crashing when talking

### ISSUE THREAD

**Issue by ujel-ragewars** [semihM/project_smok#67]
enabling project_smok and then chatting crashes the game

**project_smok version** : 
 - v3.4.0

**To Reproduce**
1. Install Left 4 Bots/Left 4 lib
2. Chat
3. Crash

**Links to other addons**
https://steamcommunity.com/sharedfiles/filedetails/?id=2279814689 - left 4 bots
https://steamcommunity.com/workshop/filedetails/?id=2634208272 - left 4 lib

**Additional context**
issue just started happening, despite the addon not updating.

**Comment by semihM** [comment]
Thanks for letting me know. Going to try figuring it out around new year's.

**Comment by semihM** [comment]
I can not reproduce this issue, everything runs as expected with Left 4 Bots addon enabled together with project_smok
